// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'fullscreenClass': string;
  'playerContainerClass': string;
  'playerMainContainerClass': string;
  'slideFramesName': string;
  'slideInterval': string;
  'slidePlayerClass': string;
  'videoPlayerClass': string;
}
export const cssExports: CssExports;
export default cssExports;
