
export type WorkFeed = FeedsData.List;

export enum WorkType {
    Video = 'video',
    Album = 'vertical',
}

// Generated by https://quicktype.io
export declare namespace FeedsData {
    export interface data {
        privateFeeds: Feeds;
        publicFeeds: Feeds;
    }

    interface Feeds {
        pcursor: string;
        list: List[];
        __typename: string;
    }

    interface List {
        id: string;
        thumbnailUrl: string;
        poster: string;
        workType: string;
        type: string;
        useVideoPlayer: boolean;
        videoUrl: string;
        imgUrls: string[];
        imgSizes: ImgSize[];
        magicFace: null;
        musicName: string;
        caption: string;
        location: null;
        liked: boolean;
        onlyFollowerCanComment: boolean;
        relativeHeight: null;
        timestamp: number;
        width: number;
        height: number;
        counts: Counts;
        likeCount: number;
        user: User;
        expTag: string;
        __typename: string;
    }

    interface Counts {
        displayView: string;
        displayLike: string;
        displayComment: string;
        __typename: string;
    }

    interface ImgSize {
        w: number;
        h: number;
    }

    interface User {
        id: string;
        eid: string;
        name: string;
        avatar: string;
        __typename: string;
    }
}
